### ISSUE TITLE
Why the test.py point_num=3000 ，However the train_multi_gpu.py point_num=2048 of part_seg ？

### ISSUE THREAD

**Issue by shengrongjin** [WangYueFt/dgcnn#25]
Thank you very much for your open source! However, I have a questi . Why the test.py point_num=3000 ，However the train_multi_gpu.py point_num=2048 of part_seg ？

**Comment by syb7573330** [comment]
Hi, thanks for reaching us out! Since the DGCNN model processes each point together with its neighboring points independently and is invariant to the number of points, it is possible to set different number of points during training and testing. Using more points during testing can accelerate inference speed.

**Comment by shengrongjin** [comment]
Thank you for your answer!
